defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
  - scope:
      path: "404.html"
    values:
      layout: error

markdown: "kramdown"

plugins:
  - jekyll-redirect-from

redirects:
  "/": "/curriculum.html"